### ISSUE TITLE
How do I initialize a project with poetry after creating a remote repo on Github?

### ISSUE THREAD

**Issue by rbardenet** [guilgautier/template-python-project#1]
I cloned an empty repo from github, cd'd to my local repo, and then ran `poetry init`. It helped me create a `.toml` file, but did not automatically create the arborescence of folders that `poetry new` would have created (i.e., src, test, and corresponding init files). Can this still be done, or should I change my way of doing things?

**Comment by guilgautier** [comment]
Hi @rbardenet 

- https://python-poetry.org/docs/cli/#new indeed generates the file/folder structure of the Python project with a `pyproject.toml` file
- https://python-poetry.org/docs/cli/#init only defines the a `pyproject.toml` file (interactively) and won't change the current file/folder structure

I suggest you do

```
poetry new repo-name --src --name package-name
cd repo-name
git init
git remote add origin https://github.com/rbardenet/repo-name.git
git pull origin main
```

Otherwise, you can also simply use the present repo as a template https://github.com/guilgautier/template-python-project/generate

**Comment by guilgautier** [comment]
Closing for now, assuming my response above answered your question.
Feel free to repoen it 😉
